# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btSign = QtWidgets.QPushButton(self.centralwidget)
        self.btSign.setGeometry(QtCore.QRect(530, 240, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btSign.setFont(font)
        self.btSign.setObjectName("btSign")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 330, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtSignature = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSignature.setGeometry(QtCore.QRect(130, 310, 321, 121))
        self.txtSignature.setObjectName("txtSignature")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 671, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btVerity = QtWidgets.QPushButton(self.centralwidget)
        self.btVerity.setGeometry(QtCore.QRect(530, 340, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btVerity.setFont(font)
        self.btVerity.setObjectName("btVerity")
        self.txtInformation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInformation.setGeometry(QtCore.QRect(130, 160, 321, 121))
        self.txtInformation.setObjectName("txtInformation")
        self.btGenerateKey = QtWidgets.QPushButton(self.centralwidget)
        self.btGenerateKey.setGeometry(QtCore.QRect(510, 180, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btGenerateKey.setFont(font)
        self.btGenerateKey.setObjectName("btGenerateKey")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btSign.setText(_translate("MainWindow", "Sign"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.btVerity.setText(_translate("MainWindow", "Verity"))
        self.btGenerateKey.setText(_translate("MainWindow", "Generate Keys"))
        self.label_4.setText(_translate("MainWindow", "Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
